version: "3"

services:

  postgres:
    image: postgres:latest
    container_name: database
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    ports:
      - '5432'

  bot:
    build: .
    restart: always
    container_name: bot
    volumes:
      - ./:/app
    command: python __main__.py
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
