"""create_tables

Revision ID: bb822ff389d6
Revises: 
Create Date: 2023-12-24 04:22:08.144690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb822ff389d6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("surname", sa.String(length=256), nullable=False),
        sa.Column("phone", sa.String(length=256), nullable=False),
        sa.Column("date_client", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "dates",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date_admin", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dates")
    op.drop_table("accounts")
    # ### end Alembic commands ###
